language: python

python:
  - "2.7"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9"
  - "3.10"

# python 3.10 requires at least Ubuntu 18.04 (bionic)
dist:
  - bionic

install:
  - pip install -e .[dev]

script:
  - make
